# Generated by Django 6.0.1 on 2026-02-09 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('restocks_inventory', models.BooleanField(default=True, help_text='Whether returning with this reason restores stock', verbose_name='Restocks Inventory')),
                ('requires_note', models.BooleanField(default=False, verbose_name='Requires Note')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Return Reason',
                'verbose_name_plural': 'Return Reasons',
                'db_table': 'returns_reason',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Return Number')),
                ('reason_notes', models.TextField(blank=True, default='', verbose_name='Reason Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Amount')),
                ('total_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Refund')),
                ('refund_method', models.CharField(choices=[('original', 'Original Payment Method'), ('cash', 'Cash'), ('store_credit', 'Store Credit')], default='original', max_length=20, verbose_name='Refund Method')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to='accounts.localuser', verbose_name='Approved By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='accounts.localuser', verbose_name='Processed By')),
                ('original_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale', verbose_name='Original Sale')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='returns.returnreason', verbose_name='Return Reason')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'returns_return',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('product_name', models.CharField(blank=True, default='', help_text='Snapshot of product name at time of return', max_length=255, verbose_name='Product Name')),
                ('product_sku', models.CharField(blank=True, default='', max_length=100, verbose_name='Product SKU')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Refund Amount')),
                ('condition', models.CharField(choices=[('new', 'New / Unopened'), ('good', 'Good Condition'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='good', max_length=20, verbose_name='Condition')),
                ('restock', models.BooleanField(default=True, help_text='Return item to inventory stock', verbose_name='Restock Item')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='inventory.product', verbose_name='Product')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return', verbose_name='Return')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='sales.saleitem', verbose_name='Original Sale Item')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'returns_return_item',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnsSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('allow_returns', models.BooleanField(default=True, verbose_name='Allow Returns')),
                ('return_window_days', models.PositiveIntegerField(default=30, help_text='Number of days after sale to allow returns', verbose_name='Return Window (Days)')),
                ('allow_store_credit', models.BooleanField(default=True, verbose_name='Allow Store Credit')),
                ('require_receipt', models.BooleanField(default=True, verbose_name='Require Receipt')),
                ('auto_restore_stock', models.BooleanField(default=True, help_text='Automatically restore inventory when return is processed', verbose_name='Auto Restore Stock')),
            ],
            options={
                'verbose_name': 'Returns Settings',
                'verbose_name_plural': 'Returns Settings',
                'db_table': 'returns_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Credit Code')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Customer Phone')),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Original Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Current Balance')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credits', to='customers.customer', verbose_name='Customer')),
                ('return_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit', to='returns.return', verbose_name='Related Return')),
            ],
            options={
                'verbose_name': 'Store Credit',
                'verbose_name_plural': 'Store Credits',
                'db_table': 'returns_store_credit',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['number'], name='returns_ret_number_30a39b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='returns_ret_status_e1e871_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-created_at'], name='returns_ret_created_36e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['code'], name='returns_sto_code_e2bf10_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['is_active'], name='returns_sto_is_acti_feabf3_idx'),
        ),
    ]
