# Generated by Django 6.0 on 2025-12-28 12:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.UUIDField(blank=True, help_text='UUID of the original sale', null=True, verbose_name='Original Sale ID')),
                ('return_number', models.CharField(blank=True, help_text='Unique identifier for this return', max_length=20, unique=True, verbose_name='Return Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this return', verbose_name='Notes')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal of returned items', max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax on returned items', max_digits=10, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to be refunded', max_digits=10, verbose_name='Total Amount')),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('store_credit', 'Store Credit'), ('original_payment', 'Original Payment Method')], default='cash', max_length=20, verbose_name='Refund Method')),
                ('processed_by', models.CharField(blank=True, help_text='User who processed the return', max_length=100, verbose_name='Processed By')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'returns_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Defective', 'Wrong Item')", max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this return reason', verbose_name='Description')),
                ('restocks_inventory', models.BooleanField(default=True, help_text='Whether returning this reason restores stock', verbose_name='Restocks Inventory')),
                ('requires_note', models.BooleanField(default=False, help_text='Whether a note is required when using this reason', verbose_name='Requires Note')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return Reason',
                'verbose_name_plural': 'Return Reasons',
                'db_table': 'returns_reason',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_returns', models.BooleanField(default=True, help_text='Enable product returns processing', verbose_name='Allow Returns')),
                ('return_window_days', models.PositiveIntegerField(default=30, help_text='Number of days after sale to allow returns', verbose_name='Return Window (Days)')),
                ('allow_store_credit', models.BooleanField(default=True, help_text='Allow refunds as store credit instead of cash', verbose_name='Allow Store Credit')),
                ('require_receipt', models.BooleanField(default=True, help_text='Require original receipt for returns', verbose_name='Require Receipt')),
                ('auto_restore_stock', models.BooleanField(default=True, help_text='Automatically restore inventory when return is processed', verbose_name='Auto Restore Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Returns Configuration',
                'verbose_name_plural': 'Returns Configuration',
                'db_table': 'returns_config',
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(blank=True, help_text='UUID of the returned product', null=True, verbose_name='Product ID')),
                ('product_name', models.CharField(help_text='Name at time of return', max_length=255, verbose_name='Product Name')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='Product SKU')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units being returned', verbose_name='Quantity Returned')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit at time of original sale', max_digits=10, verbose_name='Unit Price')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Line Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Line Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Line Total')),
                ('condition', models.CharField(choices=[('new', 'New/Unused'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20, verbose_name='Condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.return', verbose_name='Return')),
            ],
            options={
                'verbose_name': 'Return Line',
                'verbose_name_plural': 'Return Lines',
                'db_table': 'returns_line',
                'ordering': ['return_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.returnreason', verbose_name='Return Reason'),
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Credit Code')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Customer Phone')),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Original Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Current Balance')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit', to='returns.return', verbose_name='Related Return')),
            ],
            options={
                'verbose_name': 'Store Credit',
                'verbose_name_plural': 'Store Credits',
                'db_table': 'returns_store_credit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_number'], name='returns_ret_return__576d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='returns_ret_status_e1e871_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale_id'], name='returns_ret_sale_id_6ef64a_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-created_at'], name='returns_ret_created_36e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['code'], name='returns_sto_code_e2bf10_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['is_active'], name='returns_sto_is_acti_feabf3_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['customer_name'], name='returns_sto_custome_09ccf2_idx'),
        ),
    ]
