# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('returns', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale', verbose_name='Original Sale'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return', verbose_name='Return'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='sales.saleitem', verbose_name='Original Sale Item'),
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='returns.returnreason', verbose_name='Return Reason'),
        ),
        migrations.AlterUniqueTogether(
            name='returnssettings',
            unique_together={('hub_id',)},
        ),
        migrations.AddField(
            model_name='storecredit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credits', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='storecredit',
            name='return_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit', to='returns.return', verbose_name='Related Return'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['number'], name='returns_ret_number_30a39b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='returns_ret_status_e1e871_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-created_at'], name='returns_ret_created_36e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['code'], name='returns_sto_code_e2bf10_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['is_active'], name='returns_sto_is_acti_feabf3_idx'),
        ),
    ]
